Vagrant.configure("2") do |config|
  
  # 1.Ubuntu 18.04
  config.vm.define "vm1_ubuntu" do |ubuntu|
    # Вказуємо перший дистрибутив
    ubuntu.vm.box = "hashicorp/bionic64" 
    
    # Налаштовуємо ресурси для VMWare
    ubuntu.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = "1024" # Виділяємо 1 ГБ оперативної пам'яті
      v.vmx["numvcpus"] = "1"   # Виділяємо 1 ядро процесора
    end
  end

  # 2. Друга віртуальна машина: Debian 11
  config.vm.define "vm2_debian" do |debian|
    # Вказуємо інший дистрибутив
    debian.vm.box = "bento/debian-11" 
    
    # Налаштовуємо ресурси для VMWare
    debian.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = "2048" # Виділяємо 2 ГБ оперативної пам'яті
      v.vmx["numvcpus"] = "2"   # Виділяємо 2 ядра процесора
    end
  end

end